apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: lab-controller
    environment: prod
  name: lab-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lab-controller-role
subjects:
- kind: ServiceAccount
  name: lab-controller-sa
  namespace: lab-controller
