apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyI1ODY3OTQ0NTcxMTIuZGtyLmVjci5ldS13ZXN0LTIuYW1hem9uYXdzLmNvbSI6eyJhdXRoIjoiWVdWaGRXVT0ifX19
kind: Secret
metadata:
  labels:
    app: lab-controller
    environment: prod
  name: ecr-secret
  namespace: lab-controller
type: kubernetes.io/dockerconfigjson
