#!/bin/bash
set -e

echo "🔐 Setting up ArgoCD Deploy Keys for GitOps Repository..."
echo ""

mkdir -p .ssh
chmod 700 .ssh

ssh-keygen -t ed25519 -C "argocd-deploy-key" -f .ssh/argocd-deploy-key -N ""

echo ""
echo "✅ SSH keypair generated successfully!"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "📋 NEXT STEPS:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1️⃣  Add PUBLIC key to GitHub as Deploy Key:"
echo "   - Go to: https://github.com/dareyio/gitops/settings/keys"
echo "   - Click 'Add deploy key'"
echo "   - Title: 'ArgoCD Deploy Key'"
echo "   - Key: (copy the public key below)"
echo "   - ⚠️  Do NOT check 'Allow write access' (read-only)"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "PUBLIC KEY (copy this):"
echo "═══════════════════════════════════════════════════════════════"
cat .ssh/argocd-deploy-key.pub
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "2️⃣  Add PRIVATE key to Terraform Repository GitHub Secrets:"
echo "   - Go to: https://github.com/dareyio/terraform/settings/secrets/actions"
echo "   - Click 'New repository secret'"
echo "   - Name: ARGOCD_SSH_PRIVATE_KEY"
echo "   - Value: (copy the private key from the command below)"
echo ""
echo "   Run this command to copy private key:"
echo "   cat .ssh/argocd-deploy-key | pbcopy    # macOS"
echo "   cat .ssh/argocd-deploy-key | xclip     # Linux"
echo ""
echo "   Or manually:"
echo "   cat .ssh/argocd-deploy-key"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "⚠️  SECURITY NOTES:"
echo "   - Keys are stored in .ssh/ (gitignored)"
echo "   - NEVER commit these keys to git"
echo "   - Private key: .ssh/argocd-deploy-key"
echo "   - Public key: .ssh/argocd-deploy-key.pub"
echo "   - The private key goes to dareyio/terraform repository secrets"
echo "   - The public key goes to dareyio/gitops repository deploy keys"
echo ""
echo "✅ Setup complete!"

