apiVersion: v1
kind: Pod
metadata:
  name: trigger-karpenter-5th-node
  namespace: default
spec:
  containers:
    - name: test
      image: busybox:latest
      command: ["sleep", "3600"]
      resources:
        requests:
          cpu: "2"
          memory: "4Gi"
        limits:
          cpu: "2"
          memory: "4Gi"
