apiVersion: v1
kind: Pod
metadata:
  name: force-node-5
  namespace: default
spec:
  containers:
  - name: test
    image: busybox:latest
    command: ["sleep", "86400"]
    resources:
      requests:
        cpu: "2"
        memory: "4Gi"
      limits:
        cpu: "2"
        memory: "4Gi"

