apiVersion: v1
kind: Pod
metadata:
  name: maintain-node-4
  namespace: default
spec:
  containers:
  - name: test
    image: busybox:latest
    command: ["sleep", "86400"]
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
      limits:
        cpu: "1"
        memory: "2Gi"
---
apiVersion: v1
kind: Pod
metadata:
  name: maintain-node-5
  namespace: default
spec:
  containers:
  - name: test
    image: busybox:latest
    command: ["sleep", "86400"]
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
      limits:
        cpu: "1"
        memory: "2Gi"
---
apiVersion: v1
kind: Pod
metadata:
  name: maintain-node-6
  namespace: default
spec:
  containers:
  - name: test
    image: busybox:latest
    command: ["sleep", "86400"]
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
      limits:
        cpu: "1"
        memory: "2Gi"

