# Example API application using external NGINX ingress
# This template shows how to configure your APIs to be accessible from Azure frontend
#
# To deploy your actual API:
# 1. Copy this file and rename it (e.g., lab-controller-api.yaml)
# 2. Update the metadata.name, spec.source, and spec.destination
# 3. Configure ingress to use nginx-external ingress class
# 4. Add Azure frontend IPs to terraform nginx_ingress_external_allowed_ips

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://your-helm-repo.com # Your API Helm chart repo
    chart: your-api-chart # Your API Helm chart name
    targetRevision: 1.0.0
    helm:
      valuesObject:
        image:
          repository: your-api-image
          tag: latest

        service:
          type: ClusterIP
          port: 8080

        # Ingress configuration for external access
        ingress:
          enabled: true
          className: nginx-external # Uses external NGINX controller
          annotations:
            # CORS configuration for Azure frontend
            nginx.ingress.kubernetes.io/cors-allow-origin: "https://your-frontend.azurewebsites.net"
            nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS, PATCH"
            nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
            nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
            # Rate limiting
            nginx.ingress.kubernetes.io/rate-limit: "100"
            # SSL redirect
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            # External DNS annotation (optional)
            external-dns.alpha.kubernetes.io/hostname: api.talentos.darey.io
            external-dns.alpha.kubernetes.io/manage: "true"
          hosts:
            - host: api.talentos.darey.io
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: api-tls
              hosts:
                - api.talentos.darey.io

        # Environment variables
        env:
          - name: ENV
            value: "production"
          - name: LOG_LEVEL
            value: "info"

        # Resource limits
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

  destination:
    server: https://kubernetes.default.svc
    namespace: default # Or your API namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
