apiVersion: v1
kind: ServiceAccount
metadata:
  name: lab-controller-sa
  namespace: lab-controller

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lab-controller-clusterrole
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "create", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "services", "pods/log"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods/exec", "pods/attach", "pods/portforward"]
    verbs: ["create"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
  - apiGroups: ["events.k8s.io", ""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lab-controller-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: lab-controller-sa
    namespace: lab-controller
roleRef:
  kind: ClusterRole
  name: lab-controller-clusterrole
  apiGroup: rbac.authorization.k8s.io
