apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dareyscore-api
  namespace: dareyscore
  labels:
    app: dareyscore-api
    release: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    matchLabels:
      app: dareyscore-api
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
