apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  labels:
    cluster.darey.io/environment: staging
    cluster.darey.io/type: ops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 7.3.7
    helm:
      valuesObject:
        adminUser: admin
        adminPassword: admin
        persistence:
          enabled: true
          storageClassName: gp2-csi
          size: 10Gi
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
          fsGroup: 0
        containerSecurityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: false
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            cert-manager.io/cluster-issuer: letsencrypt-prod
            external-dns.alpha.kubernetes.io/hostname: grafana-stg.talentos.darey.io
            external-dns.alpha.kubernetes.io/manage: "true"
          hosts:
            - grafana-stg.talentos.darey.io
          tls:
            - secretName: grafana-stg-tls
              hosts:
                - grafana-stg.talentos.darey.io
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus (Staging Ops)
                type: prometheus
                url: http://kube-prometheus-stack-prometheus.monitoring.svc:9090
                access: proxy
                isDefault: true
                uid: prometheus-staging-ops
                jsonData:
                  timeInterval: 30s
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

