apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: lab-controller
  namespace: lab-controller
  labels:
    app: lab-controller
    release: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    matchLabels:
      app: lab-controller
  podMetricsEndpoints:
    - port: "80"
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      relabelings:
        - targetLabel: cluster
          replacement: blue

