apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dareyscore-worker
  namespace: dareyscore
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dareyscore-worker
  minReplicas: 5
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

