apiVersion: v1
kind: Service
metadata:
  name: bbb-web
  namespace: liveclasses
  labels:
    app: bbb-web
spec:
  type: ClusterIP
  selector:
    app: bbb-web
  ports:
    - name: http
      port: 80
      targetPort: 48087
      protocol: TCP

