apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: freeswitch
  namespace: liveclasses
  labels:
    app: freeswitch
spec:
  selector:
    matchLabels:
      app: freeswitch
  template:
    metadata:
      labels:
        app: freeswitch
    spec:
      # Optional: Use node selector for dedicated media processing nodes
      # nodeSelector:
      #   node-type: media-processing
      containers:
        - name: freeswitch
          image: 586794457112.dkr.ecr.eu-west-2.amazonaws.com/liveclasses/freeswitch:3.0.4
          imagePullPolicy: Always
          ports:
            - containerPort: 5060
              name: sip
              protocol: UDP
            - containerPort: 5080
              name: sip-tls
              protocol: TCP
            - containerPort: 16384
              name: rtp-start
              protocol: UDP
            - containerPort: 32768
              name: rtp-end
              protocol: UDP
          env:
            - name: FS_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: FS_ESL_PORT
              value: "8021"
            - name: FS_ESL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bbb-secrets
                  key: freeswitch-esl-password
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
                - SYS_NICE
          volumeMounts:
            - name: freeswitch-config
              mountPath: /etc/freeswitch
            - name: freeswitch-recordings
              mountPath: /var/freeswitch/recordings
      volumes:
        - name: freeswitch-config
          configMap:
            name: freeswitch-config
        - name: freeswitch-recordings
          emptyDir: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: freeswitch-config
  namespace: liveclasses
data:
  freeswitch.xml: |
    <!-- Basic FreeSWITCH configuration for BBB -->
    <!-- Full configuration should be provided via ConfigMap or mounted volume -->
