apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: liveclasses
  labels:
    app: mongodb
spec:
  serviceName: mongodb
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - mongodb
                topologyKey: kubernetes.io/hostname
          initContainers:
            - name: fix-keyfile-permissions
              image: busybox:1.36
              command:
                - sh
                - -c
                - |
                  chmod 600 /etc/mongodb-key/keyfile
                  echo "Keyfile permissions fixed"
              volumeMounts:
                - name: mongodb-key
                  mountPath: /etc/mongodb-key
            - name: init-mongodb
              image: mongo:7.0
              command:
                - bash
                - -c
                - |
                  set -e
                  if [ "$(hostname)" == "mongodb-0" ]; then
                    echo "Primary node, skipping init"
                    exit 0
                  fi
                  echo "Waiting for primary node to be ready..."
                  until mongosh --host mongodb-0.mongodb.liveclasses.svc.cluster.local:27017 --eval "db.adminCommand('ping')" --quiet; do
                    echo "Waiting for primary..."
                    sleep 2
                  done
                  echo "Primary node is ready"
              env:
                - name: MONGO_INITDB_ROOT_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: mongodb-secret
                      key: root-username
                - name: MONGO_INITDB_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mongodb-secret
                      key: root-password
              volumeMounts:
                - name: mongodb-key
                  mountPath: /etc/mongodb-key
                  readOnly: true
      containers:
        - name: mongodb
          image: mongo:7.0
          ports:
            - containerPort: 27017
              name: mongodb
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: root-password
            - name: MONGO_INITDB_DATABASE
              value: "bigbluebutton"
          command:
            - mongod
            - --bind_ip_all
            - --replSet
            - bbb-rs
            - --keyFile
            - /etc/mongodb-key/keyfile
            - --wiredTigerCacheSizeGB
            - "2"
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
            - name: mongodb-key
              mountPath: /etc/mongodb-key
              readOnly: true
            - name: mongodb-config
              mountPath: /etc/mongod.conf
              subPath: mongod.conf
          resources:
            requests:
              cpu: "1000m"
              memory: 4Gi
            limits:
              cpu: "4"
              memory: 8Gi
          livenessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: mongodb-key
          secret:
            secretName: mongodb-keyfile
        - name: mongodb-config
          configMap:
            name: mongodb-config
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp2
        resources:
          requests:
            storage: 100Gi
