apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lab-controller
  namespace: lab-controller
  labels:
    app: lab-controller
    release: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    matchLabels:
      app: lab-controller
  namespaceSelector:
    matchNames:
      - lab-controller
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s

