apiVersion: v1
kind: ConfigMap
metadata:
  name: wildcard-tls-sync-script
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
data:
  sync.sh: |
    #!/bin/bash
    set -e
    SOURCE_SECRET="wildcard-projectlabs-api-talentos-darey-io"
    SOURCE_NAMESPACE="default"
    
    # Get all namespaces ending with -lab
    kubectl get namespaces -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' | \
      grep -E "-lab$" | while read -r NS; do
        if [ -n "$NS" ]; then
          # Check if secret exists
          if ! kubectl get secret "$SOURCE_SECRET" -n "$NS" >/dev/null 2>&1; then
            echo "Syncing secret to $NS..."
            # Copy secret
            kubectl get secret "$SOURCE_SECRET" -n "$SOURCE_NAMESPACE" -o yaml | \
              sed "s/namespace: $SOURCE_NAMESPACE/namespace: $NS/" | \
              sed '/resourceVersion:/d' | \
              sed '/uid:/d' | \
              sed '/creationTimestamp:/d' | \
              sed '/selfLink:/d' | \
              kubectl apply -f -
            echo "✅ Synced to $NS"
          fi
        fi
      done
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: wildcard-tls-sync
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  schedule: "*/2 * * * *"  # Every 2 minutes
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: wildcard-tls-sync
          containers:
            - name: sync
              image: bitnami/kubectl:latest
              command:
                - /bin/bash
                - -c
                - |
                  SOURCE_SECRET="wildcard-projectlabs-api-talentos-darey-io"
                  SOURCE_NAMESPACE="default"
                  
                  # Get all namespaces ending with -lab
                  kubectl get namespaces -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' | \
                    grep -E "-lab$" | while read -r NS; do
                      if [ -n "$NS" ]; then
                        # Check if secret exists
                        if ! kubectl get secret "$SOURCE_SECRET" -n "$NS" >/dev/null 2>&1; then
                          echo "Syncing secret to $NS..."
                          # Copy secret
                          kubectl get secret "$SOURCE_SECRET" -n "$SOURCE_NAMESPACE" -o yaml | \
                            sed "s/namespace: $SOURCE_NAMESPACE/namespace: $NS/" | \
                            sed '/resourceVersion:/d' | \
                            sed '/uid:/d' | \
                            sed '/creationTimestamp:/d' | \
                            sed '/selfLink:/d' | \
                            kubectl apply -f -
                          echo "✅ Synced to $NS"
                        fi
                      fi
                    done
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
          restartPolicy: OnFailure
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wildcard-tls-sync
  namespace: default
  labels:
    app: wildcard-tls-sync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wildcard-tls-sync
  labels:
    app: wildcard-tls-sync
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wildcard-tls-sync
  labels:
    app: wildcard-tls-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wildcard-tls-sync
subjects:
  - kind: ServiceAccount
    name: wildcard-tls-sync
    namespace: default

