apiVersion: v1
kind: ConfigMap
metadata:
  name: ecr-login-script
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  ecr-login.sh: |
    #!/bin/sh
    AWS_REGION=${AWS_REGION:-eu-west-2}
    TOKEN=$(aws ecr get-authorization-token --region $AWS_REGION --output text --query "authorizationData[0].authorizationToken" 2>/dev/null)
    if [ -z "$TOKEN" ]; then
      exit 1
    fi
    DECODED=$(echo $TOKEN | base64 -d)
    USERNAME=$(echo $DECODED | cut -d: -f1)
    PASSWORD=$(echo $DECODED | cut -d: -f2-)
    echo "$USERNAME:$PASSWORD"

