# ArgoCD Cluster Secret Template for staging-workload cluster
#
# IMPORTANT: This file is a template/documentation. The actual secret contains sensitive
# bearer tokens and cannot be committed to Git. It must be created manually or via script
# using values from Terraform outputs.
#
# To create the actual secret:
#
# Option 1: Using ArgoCD CLI (Recommended)
#   1. Ensure kubeconfig has staging-workload cluster context configured
#   2. Get cluster endpoint from Terraform: terraform -chdir=../../terraform/environments/staging output -raw workload_cluster_endpoint
#   3. Run: argocd cluster add <staging-workload-context-name> --name staging-workload --server <endpoint>
#
# Option 2: Using kubectl with Terraform outputs
#   1. Get cluster endpoint: STAGING_ENDPOINT=$(terraform -chdir=../../terraform/environments/staging output -raw workload_cluster_endpoint)
#   2. Get CA cert: STAGING_CA=$(terraform -chdir=../../terraform/environments/staging output -raw workload_cluster_ca)
#   3. Create ServiceAccount and get bearer token in staging-workload cluster
#   4. Create secret:
#      kubectl create secret generic staging-workload-cluster-secret \
#        --from-literal=name=staging-workload \
#        --from-literal=server=https://${STAGING_ENDPOINT} \
#        --from-literal=config="{\"bearerToken\":\"<token>\",\"tlsClientConfig\":{\"caData\":\"${STAGING_CA}\",\"insecure\":false}}" \
#        --type=Opaque -n argocd --context prod-ops
#   5. Label it: kubectl label secret staging-workload-cluster-secret -n argocd argocd.argoproj.io/secret-type=cluster --context prod-ops
#
# After creation, ArgoCD will automatically discover and use this secret to manage the staging-workload cluster.
