apiVersion: batch/v1
kind: Job
metadata:
  name: dareyscore-migration
  namespace: dareyscore
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: dareyscore-sa
      restartPolicy: OnFailure
      containers:
        - name: migration
          image: 586794457112.dkr.ecr.eu-west-2.amazonaws.com/dareyscore/dareyscore-api:e0386777a11eb8759a94fc42ae23402b1de011c5
          imagePullPolicy: Always
          command:
            - alembic
            - upgrade
            - head
          envFrom:
            - configMapRef:
                name: dareyscore-config
            - secretRef:
                name: dareyscore-api-secrets
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
