apiVersion: batch/v1
kind: Job
metadata:
  name: dareyscore-migration
  namespace: dareyscore
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: dareyscore-sa
      restartPolicy: OnFailure
      containers:
        - name: migration
          image: 586794457112.dkr.ecr.eu-west-2.amazonaws.com/dareyscore/dareyscore-api:39dc24ac10055f068bca28ba0e9951cd1607e480
          imagePullPolicy: Always
          command:
            - alembic
            - upgrade
            - head
          envFrom:
            - configMapRef:
                name: dareyscore-config
            - secretRef:
                name: dareyscore-api-secrets
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
