apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: dareyscore
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
    - port: 9121
      targetPort: 9121
      name: metrics
