apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis
  namespace: dareyscore
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: redis
  namespaceSelector:
    matchNames:
      - dareyscore
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s

