apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
  namespace: karpenter
spec:
  amiFamily: AL2
  role: darey-io-v2-lab-prod-karpenter-instance-profile
  subnetSelectorTerms:
    - id: subnet-071727569182dc738
    - id: subnet-0962da11cb794b5ee
  securityGroupSelectorTerms:
    - id: sg-0a6711f4fe162b935
  tags:
    Environment: production
    Project: darey-io-v2-lab
    Terraform: "true"
    Owner: dare@darey.io
    CostCenter: engineering
    Compliance: required
    Backup: required
