apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dareyscore
  namespace: argocd
  labels:
    cluster.darey.io/colour: blue
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/dareyio/gitops.git
    targetRevision: HEAD
    path: argocd/applications/prod-blue/dareyscore
  destination:
    # NOTE: Update this to prod-blue cluster endpoint after cluster is created
    server: https://DA6D72227F1F84B2237A1AB7DF222FD1.gr7.eu-west-2.eks.amazonaws.com
    namespace: dareyscore
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 3
