apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.10.0
    helm:
      valuesObject:
        # Disable Loki chart from creating a Grafana datasource ConfigMap
        grafana:
          enabled: false
          sidecar:
            datasources:
              enabled: false
        loki:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
          persistence:
            enabled: true
            size: 5Gi
            storageClassName: gp2-eks-csi
            accessModes:
              - ReadWriteOnce
        promtail:
          enabled: true
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 384Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
