apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.10.0
    helm:
      valuesObject:
        # Disable Loki chart from creating a Grafana datasource ConfigMap
        grafana:
          enabled: false
          sidecar:
            datasources:
              enabled: false
        loki:
          enabled: false
        promtail:
          enabled: true
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 384Mi
          config:
            clients:
              - url: https://loki-ops.internal.talentos.darey.io/loki/api/v1/push
                tenant_id: "1"
                tls_config:
                  insecure_skip_verify: true
  destination:
    # NOTE: Update this to prod-blue cluster endpoint after cluster is created
    server: https://05EAD20A36B7EEE44B5F80407DFE359B.sk1.eu-west-2.eks.amazonaws.com
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
