apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dareyscore
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:dareyio/gitops.git
    targetRevision: HEAD
    path: argocd/applications/prod/dareyscore
  destination:
    server: https://kubernetes.default.svc
    namespace: dareyscore
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 3
