apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns
    chart: external-dns
    targetRevision: 1.13.1
    helm:
      valuesObject:
        replicaCount: 2
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::586794457112:role/prod-external-dns-role
        provider: aws
        aws:
          region: eu-west-2
          zoneType: public
        domainFilters:
          - talentos.darey.io
        policy: upsert-only
        txtOwnerId: external-dns
        logFormat: json
        logLevel: info
        sources:
          - ingress
          - service
        ingress:
          enabled: true
        service:
          enabled: true
        # Prevent deletion of manually created records
        registry:
          txt:
            ownerId: external-dns
        # Only manage records with specific annotations
        annotationFilter: "external-dns.alpha.kubernetes.io/manage=true"
        podSecurityContext:
          fsGroup: 65534
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
