apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-controller-app
  namespace: argocd
  labels:
    app: lab-controller
    environment: prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:dareyio/gitops.git
    targetRevision: main
    path: argocd/lab-applications/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: lab-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
