apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.10.0
    helm:
      valuesObject:
        # Disable Loki chart from creating a Grafana datasource ConfigMap
        grafana:
          enabled: false
          sidecar:
            datasources:
              enabled: false
        loki:
          persistence:
            enabled: true
            size: 10Gi
            storageClass: "gp2-eks-csi"
        promtail:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
