apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.139.0
    helm:
      valuesObject:
        mode: deployment
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        ports:
          otlp:
            enabled: true
            containerPort: 4317
            servicePort: 4317
            hostPort: null
            appProtocol: grpc
          otlp-http:
            enabled: true
            containerPort: 4318
            servicePort: 4318
            hostPort: null
          metrics:
            enabled: true
            containerPort: 8888
            servicePort: 8888
        service:
          type: ClusterIP
        serviceMonitor:
          enabled: true
          extraLabels:
            release: kube-prometheus-stack
        config:
          exporters:
            logging:
              loglevel: warn
            otlp/tempo:
              endpoint: tempo.observability.svc.cluster.local:4317
              tls:
                insecure: true
          extensions:
            health_check:
              endpoint: ${env:MY_POD_IP}:13133
          processors:
            batch: {}
            memory_limiter:
              check_interval: 5s
              limit_percentage: 80
              spike_limit_percentage: 25
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: ${env:MY_POD_IP}:4317
                http:
                  endpoint: ${env:MY_POD_IP}:4318
          service:
            telemetry:
              metrics:
                readers:
                  - pull:
                      exporter:
                        prometheus:
                          host: ${env:MY_POD_IP}
                          port: 8888
            extensions:
              - health_check
            pipelines:
              traces:
                receivers: [otlp]
                processors: [memory_limiter, batch]
                exporters: [otlp/tempo]
              metrics:
                receivers: [otlp]
                processors: [memory_limiter, batch]
                exporters: [logging]
              logs:
                receivers: [otlp]
                processors: [memory_limiter, batch]
                exporters: [logging]
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

