apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-image-updater
    targetRevision: 0.9.1
    helm:
      valuesObject:
        config:
          registries:
            - name: AWS ECR
              prefix: 586794457112.dkr.ecr.eu-west-2.amazonaws.com
              api_url: https://586794457112.dkr.ecr.eu-west-2.amazonaws.com
              ping: no
              default: true
              credentials: secret:argocd/argocd-image-updater-ecr#username:password
              credsexpiry: 12h
          git:
            writeBackMethod: git
            branch: main
            commitMessageTemplate: |
              build: update {{.AppName}} image {{.ImageName}} to {{.NewTag}}
              [ci skip]
            pull:
              enabled: true
              interval: 1m
        serviceAccount:
          create: true
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::586794457112:role/darey-io-v2-lab-prod-ops-external-secrets-operator-role
        extraEnv:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: argocd-image-updater-ecr
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: argocd-image-updater-ecr
                key: aws_secret_access_key
        gitSecret:
          create: false
          name: argocd-repo-ssh
          key: sshPrivateKey
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

