apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-cost-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/dareyio/gitops.git
    targetRevision: main
    path: argocd/applications/prod-ops/applications/aws-cost-exporter
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: finops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
