apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-cost-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/grafana/helm-charts
    chart: aws-cost-exporter
    targetRevision: 0.1.0
    helm:
      valuesObject:
        image:
          repository: prom/cloudwatch-exporter
          tag: latest
          pullPolicy: IfNotPresent
        serviceAccount:
          create: true
          name: aws-cost-exporter
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::586794457112:role/darey-io-v2-lab-prod-ops-aws-cost-exporter-role
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        config:
          region: eu-west-2
          metrics:
            - aws_namespace: AWS/Billing
              aws_metric_name: EstimatedCharges
              aws_dimensions: [ServiceName, Currency]
              aws_statistics: [Maximum]
              range_seconds: 86400
              period_seconds: 3600
        service:
          type: ClusterIP
          port: 9106
        serviceMonitor:
          enabled: true
          interval: 1h
          scrapeTimeout: 30s
          labels:
            release: kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

