apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.10.0
    helm:
      valuesObject:
        grafana:
          enabled: false
          sidecar:
            datasources:
              enabled: false
        loki:
          enabled: true
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          persistence:
            enabled: true
            size: 50Gi
            storageClassName: gp2-eks-csi
            accessModes:
              - ReadWriteOnce
          config:
            auth_enabled: false
            server:
              http_listen_port: 3100
              grpc_listen_port: 9096
            schema_config:
              configs:
                - from: "2020-10-24"
                  store: boltdb-shipper
                  object_store: filesystem
                  schema: v11
                  index:
                    prefix: index_
                    period: 24h
            storage_config:
              boltdb_shipper:
                active_index_directory: /data/boltdb-shipper-active
                cache_location: /data/boltdb-shipper-cache
                shared_store: filesystem
              filesystem:
                directory: /data/chunks
            limits_config:
              enforce_metric_name: false
              reject_old_samples: true
              reject_old_samples_max_age: 168h
        promtail:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
