apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: 1.24.0
    helm:
      valuesObject:
        tempo:
          retention: 168h
          storage:
            trace:
              backend: local
              local:
                path: /var/tempo/traces
              wal:
                path: /var/tempo/wal
          metricsGenerator:
            enabled: true
            remoteWriteUrl: "http://kube-prometheus-stack-prometheus.monitoring.svc:9090/api/v1/write"
            storage:
              path: /var/tempo/generator/wal
          overrides:
            defaults:
              metrics_generator:
                processors:
                  - service-graphs
                  - span-metrics
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 2Gi
        persistence:
          enabled: true
          storageClassName: gp2-eks-csi
          size: 50Gi
          accessModes:
            - ReadWriteOnce
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: gp2-eks-csi
            resources:
              requests:
                storage: 50Gi
        serviceMonitor:
          enabled: true
          extraLabels:
            release: kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
