apiVersion: v1
kind: Service
metadata:
  name: thanos-receive
  namespace: monitoring
spec:
  ports:
    - name: http
      port: 10902
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 10901
      targetPort: grpc
      protocol: TCP
    - name: remote-write
      port: 19291
      targetPort: remote-write
      protocol: TCP

