apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-thanos-receive-0
  namespace: monitoring
  labels:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/component: receive
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2-eks-csi
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-thanos-receive-1
  namespace: monitoring
  labels:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/component: receive
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2-eks-csi
  resources:
    requests:
      storage: 50Gi

