apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanos-receive-patch
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/dareyio/gitops.git
    targetRevision: main
    path: argocd/applications/prod-ops/applications/thanos-receive-statefulset-patch.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true

