apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanos
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: thanos
    targetRevision: 12.6.1
    helm:
      valuesObject:
        query:
          enabled: true
          replicaCount: 2
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          service:
            type: ClusterIP
          serviceMonitor:
            enabled: true
          # Store configuration - Thanos Query will query Thanos Receive
          # Receive aggregates metrics from all Prometheus instances via remoteWrite
          # Using gRPC endpoint for store API
          storeEndpoints:
            - thanos-receive.monitoring.svc.cluster.local:10901
        store:
          enabled: true
          replicaCount: 2
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 8Gi
          service:
            type: ClusterIP
          serviceMonitor:
            enabled: true
          objstoreConfig: |
            type: S3
            config:
              bucket: darey-io-v2-lab-prod-thanos-storage
              endpoint: s3.eu-west-2.amazonaws.com
              region: eu-west-2
              sse_config:
                type: SSE-S3
          serviceAccount:
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::586794457112:role/darey-io-v2-lab-prod-ops-thanos-role
        compactor:
          enabled: true
          replicaCount: 1
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          serviceMonitor:
            enabled: true
          objstoreConfig: |
            type: S3
            config:
              bucket: darey-io-v2-lab-prod-thanos-storage
              endpoint: s3.eu-west-2.amazonaws.com
              region: eu-west-2
              sse_config:
                type: SSE-S3
          serviceAccount:
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::586794457112:role/darey-io-v2-lab-prod-ops-thanos-role
        queryFrontend:
          enabled: false
        bucketweb:
          enabled: false
        ruler:
          enabled: false
        receive:
          enabled: true
          replicaCount: 2
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          service:
            type: ClusterIP
          serviceMonitor:
            enabled: true
          serviceAccount:
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::586794457112:role/darey-io-v2-lab-prod-ops-thanos-role
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
