apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanos
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: thanos
    targetRevision: "12.6.1"
    helm:
      valuesObject:
        image:
          registry: quay.io
          repository: thanos/thanos
          tag: v0.31.0
          pullPolicy: IfNotPresent
        query:
          enabled: true
          replicaCount: 2
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          http:
            port: 10902
          service:
            type: ClusterIP
            ports:
              http: 10902
          serviceMonitor:
            enabled: true
          # Store configuration - Thanos Query will query Thanos Receive
          # Receive aggregates metrics from all Prometheus instances via remoteWrite
          # Using gRPC endpoint for store API
          # Note: Store component is enabled but not yet running - will add when available
          storeEndpoints:
            - thanos-receive.monitoring.svc.cluster.local:10901
        objstoreConfig: |
          type: S3
          config:
            bucket: darey-io-v2-lab-prod-thanos-storage
            endpoint: s3.eu-west-2.amazonaws.com
            region: eu-west-2
            sse_config:
              type: SSE-S3
        store:
          enabled: true
          replicaCount: 2
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 8Gi
          service:
            type: ClusterIP
          serviceMonitor:
            enabled: true
          serviceAccount:
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::586794457112:role/darey-io-v2-lab-prod-ops-thanos-role
        compactor:
          enabled: true
          replicaCount: 1
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          persistence:
            enabled: true
            storageClass: efs-sc
            accessModes:
              - ReadWriteMany
            size: 10Gi
          serviceMonitor:
            enabled: true
          serviceAccount:
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::586794457112:role/darey-io-v2-lab-prod-ops-thanos-role
        queryFrontend:
          enabled: false
        bucketweb:
          enabled: false
        ruler:
          enabled: false
        receive:
          enabled: true
          replicaCount: 2
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          service:
            type: LoadBalancer
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
            ports:
              - name: http
                port: 10902
                targetPort: http
              - name: grpc
                port: 10901
                targetPort: grpc
              - name: remote-write
                port: 19291
                targetPort: remote-write
          # Persistence removed from Helm to avoid template conflict
          # PVCs will be created manually and StatefulSet patched separately
          serviceMonitor:
            enabled: true
          serviceAccount:
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::586794457112:role/darey-io-v2-lab-prod-ops-thanos-role
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
