apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kurento-media-server
  namespace: liveclasses
  labels:
    app: kurento-media-server
spec:
  selector:
    matchLabels:
      app: kurento-media-server
  template:
    metadata:
      labels:
        app: kurento-media-server
    spec:
      # Optional: Use node selector for dedicated media processing nodes
      # nodeSelector:
      #   node-type: media-processing
      containers:
        - name: kurento
          image: bigbluebutton/kurento-media-server:3.0.4
          ports:
            - containerPort: 8888
              name: websocket
              protocol: TCP
            - containerPort: 5000
              name: rtp-start
              protocol: UDP
            - containerPort: 65535
              name: rtp-end
              protocol: UDP
          env:
            - name: KURENTO_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KURENTO_WS_URI
              value: "ws://kurento-media-server:8888/kurento"
          resources:
            requests:
              cpu: 2000m
              memory: 4Gi
            limits:
              cpu: 4000m
              memory: 8Gi
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
                - SYS_NICE
          volumeMounts:
            - name: kurento-config
              mountPath: /etc/kurento
      volumes:
        - name: kurento-config
          configMap:
            name: kurento-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kurento-config
  namespace: liveclasses
data:
  kurento.conf.json: |
    {
      "mediaServer": {
        "resources": {
          "garbageCollectorPeriod": 240,
          "threadPoolSize": 20
        }
      }
    }

