apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-backup
  namespace: liveclasses
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::586794457112:role/darey-v2-prod-workload-liveclasses-recordings-role

