apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: liveclasses
type: Opaque
stringData:
  root-username: "mongodb-admin"
  root-password: "CHANGE_ME_IN_PRODUCTION"
  database-name: "bigbluebutton"
  database-username: "bbb"
  database-password: "CHANGE_ME_IN_PRODUCTION"

